# https://docs.github.com/ja/actions/reference/events-that-trigger-workflows#workflow_dispatch
name: Manually triggered workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

jobs:
  release:
    name: Node.js ubuntu-latest 14.x
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: yarn install
#       - run: yarn release
      - run: |
          echo "${{ github.actor }}"

